# Copyright 2011 Redpill-Linpro AS.
#
# This file is part of Foyer.
#
# Foyer is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Foyer is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Foyer. If not, see <http://www.gnu.org/licenses/>.

# This file is loaded after schema.rb during a rake db:schema:load. It is not
# autogenerated, so you can safely edit this file. It exists to add extra
# modifications to the database that db:schema:dump does not create
# automatically for us (e.g. foreign keys).

# NOTE: If you add anything here, remember to create a migration for it so that
# active databases get these changes as well (not just new ones) and vica versa
# (add special stuff from migrations here).
ActiveRecord::Schema.define do

  # Migration 015_case_insensitive_customer_names:
  execute %(CREATE UNIQUE INDEX customers_lower_name_index on customers (lower(name));)

  # Migration 016_add_foreign_keys:

  # Make sure the tables with custom ID column actually marks the id-field as
  # primary:
  %w(users roles customers).each do |table|
    execute %{ALTER TABLE #{table} ADD PRIMARY KEY (id);}
  end

  # Add all associations as foreign keys in order to guard against data
  # corruption (which could manifest itself via the ldap sync script).
  #
  # User and customer table are synced via LDAP. Any constraints associated
  # with those tables must therefore be deferrable.
  add_foreign_key :customer_portlet_relation, :customer,                    :deferrable => true,  :cascade_delete => true
  add_foreign_key :customer_portlet_relation, :user, :created_by_user_id,   :deferrable => true
  add_foreign_key :customer_portlet_relation, :user, :updated_by_user_id,   :deferrable => true

  add_foreign_key :customer, :user, :created_by_user_id,                    :deferrable => true
  add_foreign_key :customer, :user, :updated_by_user_id,                    :deferrable => true

  add_foreign_key :role, :user, :created_by_user_id,                        :deferrable => true
  add_foreign_key :role, :user, :updated_by_user_id,                        :deferrable => true

  add_foreign_key :user_customer_relation, :user,                           :deferrable => true,  :cascade_delete => true
  add_foreign_key :user_customer_relation, :customer,                       :deferrable => true,  :cascade_delete => true
  add_foreign_key :user_customer_relation, :user, :created_by_user_id,      :deferrable => true
  add_foreign_key :user_customer_relation, :user, :updated_by_user_id,      :deferrable => true

  add_foreign_key :user, :role
  add_foreign_key :user, :user, :created_by_user_id,                        :deferrable => true
  add_foreign_key :user, :user, :updated_by_user_id,                        :deferrable => true

  # Migration 017_create_portlet_attributes:
  add_foreign_key :portlet_attribute, :customer_portlet_relation,                                 :cascade_delete => true
  add_foreign_key :portlet_attribute, :user, :created_by_user_id,           :deferrable => true
  add_foreign_key :portlet_attribute, :user, :updated_by_user_id,           :deferrable => true

end